Fix libwtk_sdl2_test-gui link error
```
/usr/bin/ld: libwtk_sdl2_test-gui.o: undefined reference to symbol 'TTF_Init'
/usr/bin/ld: //usr/lib/arm-linux-gnueabihf/libSDL2_ttf-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:573: libwtk-sdl2-test] Error 1
```